trigger:
- '*'

variables:
- name: showTestStage
  value: false

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: VMSS-AGENT
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'echo ''Hello world'''


- stage: Release
  condition: and(succeeded(), eq(variables['showTestStage'], 'true'))
  displayName: Release
  jobs:
  - job: release
    displayName: Release
    pool:
      name: Azure Pipelines
    steps:               
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'echo ''Hello world'''