trigger:
- '*'

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: Azure Pipelines
      vmImage: 'windows-latest'
    steps:
      - task: PowerShell@1    
        displayName: Print hello World must be success
        inputs:
          scriptType: inlineScript
          inlineScript: > 
            echo Hello world


- stage: Release
  displayName: Release
  jobs:
  - job: release
    displayName: Release
    pool:
      name: VMSS-AGENT
    steps:               
      - task: PowerShell@1
        continueOnError: true
        displayName: task that would fail                  
        inputs:
          scriptType: inlineScript
          inlineScript: >
            echo $(testvariable)

      # - task: PowerShell@1
      #   displayName: print hello
      #   inputs:
      #     scriptType: inlineScript
      #     inlineScript: >
      #       echo hello