trigger:
- '*'

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: Azure Pipelines
      vmImage: 'windows-latest'
    steps:
      - task: PowerShell@1    
        displayName: Create build container
        inputs:
          scriptType: inlineScript
          inlineScript: > 
            echo Hello world


- stage: Release
  displayName: Release
  jobs:
  - job: release
    displayName: Release
    pool:
      name: Azure Pipelines
      vmImage: 'windows-latest'
      demands: xcode
    steps:               
      - task: PowerShell@1
        continueOnError: true
        displayName: Copy artifacts to release directory                  
        inputs:
          scriptType: inlineScript
          inlineScript: >
            echo $(testvariable)

      - task: PowerShell@1
        displayName: Publish and install app into container
        inputs:
          scriptType: inlineScript
          inlineScript: >
            echo hello