# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- $PAT = cxa6njob3p64nghathzncbiovnfpbyqlu3rbwuy4goagrcqciema
$connectionToken="$($PAT)"
$base64AuthInfo= [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes(":$($connectionToken)"))




$releaseURL= "https://vsrm.dev.azure.com/Ashisbhatt0517/First_project/_apis/release/releases?api-version=7.1-preview.8"



#Request Body
$body =
'{
"definitionId": 13,
"description": "Creating_release",
"artifacts": [
{
"alias": "Validate_Pull_Request",
"instanceReference": {
"id": "261",
"name": "Validate_Pull_Request"
},



"alias1": "ValidatePullRequestMaster",
"instanceReference": {
"id": "444",
"name": "ValidatePullRequestMaster"
}
}
],
"isDraft": false,
"reason": "testing purpose",
"manualEnvironments": null,
"environmentsMetadata": null,
"properties": null,
"variables": null
}'




$result = Invoke-RestMethod -Uri $releaseURL -Headers @{ Authorization = ("Basic {0}" -f $base64AuthInfo) } -Method POST -Body $body -ContentType "application/json"



Write-Host $result | ConvertTo-Json
