trigger:
- '*'

pool:
  name: Azure Pipelines

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: Azure Pipelines
    steps:
      - task: PowerShell@1    
        displayName: Create build container
        inputs:
          scriptType: inlineScript
          inlineScript: > 
            echo Hello world


- stage: Release
  displayName: Release
  jobs:
  dependsOn: build
  condition: Succeeded()
  - deployment:
    displayName: Release
    pool:
      name: Azure Pipelines
      demands: xcode
    environment: Release
    strategy:
      runOnce:
        deploy:
          steps:               
            - task: PowerShell@1
              continueOnError: true
              displayName: Copy artifacts to release directory                  
              inputs:
                scriptType: inlineScript
                inlineScript: >
                  echo $(testvariable)