trigger:
- '*'
pool:
      name: VMSS-AGENT
stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: VMSS-AGENT
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'echo ''Hello world'''


- stage: Release
  displayName: Release
  jobs:
  - job: release
    displayName: Release
    pool:
      name: VMSS-AGENT
    steps:               
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'echo ''Hello world'''

      # - task: PowerShell@1
      #   displayName: print hello
      #   inputs:
      #     scriptType: inlineScript
      #     inlineScript: >
      #       echo hello
